spring.application.name=bookshelf

# Carrega as credenciais do arquivo na raiz do projeto
spring.config.import=file:./.env[.properties]

# Conexao com PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false